### ISSUE TITLE
BFF failed to trigger on KDE application crash

### ISSUE THREAD

**Issue by adarshdinesh** [CERTCC/certfuzz#1]
#0  0x00007ff086456cc9 in raise () from /lib/x86_64-linux-gnu/libc.so.6 (SIGNAL Re-raised from crash handler)
#1  0x00007ff08863b182 in KCrash::defaultCrashHandler(int) () from /usr/lib/libkdeui.so.5 (Crash handler spawned)
#2  <signal handler called>
#3  0x00007ff072ebb937 in ?? () from /usr/lib/kde4/okularGenerator_xps.so (Crash happened here with SIGSEGV)
#4  0x00007ff072ec220c in ?? () from /usr/lib/kde4/okularGenerator_xps.so
#5  0x00007ff072ec2b00 in ?? () from /usr/lib/kde4/okularGenerator_xps.so
#6  0x00007ff0773d23b1 in ?? () from /usr/lib/libokularcore.so.4
#7  0x00007ff0773d2905 in Okular::Document::openDocument(QString const&, KUrl const&, KSharedPtr<KMimeType> const&) ()

   from /usr/lib/libokularcore.so.4
#8  0x00007ff077695cac in Okular::Part::openFile() () from /usr/lib/kde4/okularpart.so
#9  0x00007ff0890ecc47 in ?? () from /usr/lib/libkparts.so.4
#10 0x00007ff0890ee22e in KParts::ReadOnlyPart::openUrl(KUrl const&) () from /usr/lib/libkparts.so.4
#11 0x00007ff07768b10b in Okular::Part::openUrl(KUrl const&) () from /usr/lib/kde4/okularpart.so
#12 0x000000000040f117 in _start ()

The signal was handled from the code and "KDE Handler process" was spawned and signal raised again from there (Re-raising signal for Apport handling.) which will make it impossible for BFF to trigger.
Set $KDE_DEBUG to avoid KDE applications from crash-handling

**Comment by wdormann** [comment]
This was fixed in https://github.com/CERTCC-Vulnerability-Analysis/certfuzz/commit/6cd8bb86fdf6c24e88318adf158ab2b0e6c1fc75   (which is in BFF 2.8)
