### ISSUE TITLE
"Is memory randomization disabled"

### ISSUE THREAD

**Issue by b0nd** [CERTCC/certfuzz#14]
Hi,
On windows prompt, quite often I see 'Too many crash hashes seen to minimize. Is memory randomization disabled?' and I see it comes from module minimizer_base.py. 
May I know the draw backs of it? Anyway I could improve upon?
I am on platform Windows7 x86. 

Thanks in advance!

**Comment by wdormann** [comment]
Some crashes aren't consistent, and they cannot be minimized because of this.  There's not really anything that can be done about it.  The memory randomization message is relevant on nonwindows platforms, where it can make a difference.
