### ISSUE TITLE
Fuzz static read files instead of cmdline target file 

### ISSUE THREAD

**Issue by 444xxk** [CERTCC/certfuzz#16]
Hello im trying to hack into your fuzzer to make it fuzz files read statically by binaries. 
For instance: Binary.exe loads C:\staticpath\intro.mp3   

I m trying to fuzz the file **in place** using hardlinks and similar but it seems not straight forward with BFF. How would you achieve that quickly ?  Can it be a feature ?

**Comment by wdormann** [comment]
I actually just did something like this recently.  It's not efficient, as it creates an additional copy of the target file for each iteration, but it got the job done.  I've attached a copy of the diff that would work for your case.  Obviously, modify as necessary to fit your needs.   The changes are trivial enough that you could probably just modify the files by hand, if you don't have patch tools in your VM.

I'll leave this open as an enhancement request.

[BFF-fixed_path.diff.txt](https://github.com/CERTCC-Vulnerability-Analysis/certfuzz/files/1079245/BFF-fixed_path.diff.txt)

**Comment by 444xxk** [comment]
ah many thanks !! i see your changes, i was  trying to modify the seedfile_set.py function copy_file_from_origin instead but i ll try your patch. With this change we are able to fuzz much more things (and i like the speed of BFF) thanks again. 

EDIT: patch tested and working fine 
dont forget to delete your .pyc for recompiling with changes

**Comment by antnks** [comment]
I was also looking for a hardcoded file fuzz. This patch helped

**Comment by b0nd** [comment]
404 for BFF-fixed_path.diff.txt

**Comment by wdormann** [comment]
Oh, try this instead:
https://github.com/CERTCC/certfuzz/files/1079245/BFF-fixed_path.diff.txt
