### ISSUE TITLE
CertBFF isn't logging crashes as Microsoft visual c++ runtime library handles them 

### ISSUE THREAD

**Issue by safdar-aneela** [CERTCC/certfuzz#35]
Hi,

I am trying to learn certfbff and therefore created a simple GUI application that takes a command line argument txt file. It crashes if any other type is given. Now when I try to fuzz it with BFF, any corrupt input given to it causes application to crash but MS visual C++ Runtime library handles crashes and BFF doesn't log anything as crash. 

What is good way to learn this fuzzer? Is there any problem of managed code here that wont BFF to detect crashes? How can I fuzz such applications?

**Comment by wdormann** [comment]
If it's managed code, then it may not be vulnerable to traditional memory corruption bugs, which is what BFF can find.  Just to be clear as to what is happening, can you post a screenshot or other details that describe what you mean by "MS visual C++ Runtime library handles crashes" ?

**Comment by safdar-aneela** [comment]
Hi,

Thank you for prompt response, I didn't find any forum/group of BFF so had to post here.

I basically want to fuzz a simple GUI application so I made one for that pupose. I first used Visual Studio but it was adding Common Language Runtime features as I starting using GUI items, so I left that  (i didn't want to use managed code). Then I used Dev C++ and with win32 api I created an application which opens a file (.txt) both from menu and command line argument as well (GUI.exe test.txt) to sum up digits in file and display result. I also created an intentional abort() call in program for an input scenario to check fuzzing success. Now when I fuzz it with BFF and added some jpg in seed directory to make sure crashes. Application stops working and i get Microsoft Visual C++ Runtime Library popup saying 'The application has requested runtime to terminate it in unusal way'. No crashes logged in BFF.

I think using win32 API has made my code managed (I am not sure about this at all). Its a simple GUI which is crashing but how can I able to fuzz it properly with BFF. I want a GUI fuzzing tool for my project and no luck till now.

Attached is my code, bff config file and screenshot of error.
![bff](https://user-images.githubusercontent.com/46552122/60318894-1815d300-998e-11e9-8039-148505c7ed1e.png)
[code.txt](https://github.com/CERTCC/certfuzz/files/3337631/code.txt)
[bff.txt](https://github.com/CERTCC/certfuzz/files/3337634/bff.txt)

**Comment by wdormann** [comment]
calling abort() will result in such a message, so this is expected. abort() exits the current process, setting an exit code value.   It's not a crash, and therefore BFF isn't interested in it.

**Comment by safdar-aneela** [comment]
Ok thank you. Can you please suggest a c++ way to deliberately crash
application which BFF can detect and log instead what happening now?

**Comment by wdormann** [comment]
If you want to see apps crash, I suggest just using the default-configured ImageMagick that comes with BFF.  As for how to write vulnerable code, that's a bit out of scope for here.  I'm sure you can search for things.

**Comment by safdar-aneela** [comment]
Thank you for your answers.

I have one more query regarding what is happening here.
abort() is funtion I am calling delibrately but what if I give it non .txt files. It still crashes. Shouldn't BFF be interested in such crashes?
