### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Kwame-NrD** [CERTCC/certfuzz#37]
I'm trying to run BFF on windows. Trying the magic example first .. after moving certain files (bff.yaml) to where they should be 
bff.py starts running, seedfiles get generated, target file executes correctly but then when the campaign attempts to start I get the following error :
`2020-11-15 18:08:00,210 WARNING certfuzz.iteration.iteration_windows - WindowsIteration terminating abnormally due to WindowsError: [Error 2] The system cannot find the file specified`
BFF log file :
`2020-11-15 18:07:49,930 INFO certfuzz.campaign.campaign_base - No cached campaign data found, will proceed as new campaign: [Errno 2] No such file or directory: 'C:\\BFF\\src\\fuzzdir\\campaign_convert_v5_5_7.json'
2020-11-15 18:07:49,930 INFO certfuzz.campaign.campaign_windows - Invoking ['C:\\BFF\\imagemagick\\convert.exe', 'C:\\BFF\\src\\fuzzdir\\campaign_w6wubz\\seedfiles\\sf_b96c20e313b20e917bc0de2efacfec48.tim']
2020-11-15 18:07:50,075 INFO certfuzz.campaign.campaign_windows - Please ensure that the target program has just executed successfully
2020-11-15 18:08:00,075 INFO certfuzz.bff.common - Starting campaign
2020-11-15 18:08:00,115 INFO certfuzz.campaign.campaign_base - Selected seedfile: sf_482b40a36e377b5cba922535fe4db5df.xpm
2020-11-15 18:08:00,210 WARNING certfuzz.iteration.iteration_windows - WindowsIteration terminating abnormally due to WindowsError: [Error 2] The system cannot find the file specified`

I did not notice " campaign_convert_v5_5_7.json " getting created in fuzzdir, the seedfiles do and then get deleted as it's a temp directory I assume. I don't think that's the issue but which file is the system unable to find exactly ?

**Comment by wdormann** [comment]
As the log reports, C:\BFF\\imagemagick\convert.exe doesn't seem to be there.
If it's not there, might I ask if you installed BFF using [the installer](https://resources.sei.cmu.edu/forms/bff-download.cfm)?

certfuzz itself isn't a fuzzer.  It's a framework with which the BFF fuzzer is built.

**Comment by Kwame-NrD** [comment]
My bad, I didn't use the installer at all . I've only been working with the scripts. Thank you !

**Comment by Kwame-NrD** [comment]
> As the log reports, C:\BFF\imagemagick\convert.exe doesn't seem to be there.
> If it's not there, might I ask if you installed BFF using [the installer](https://resources.sei.cmu.edu/forms/bff-download.cfm)?
> 
> certfuzz itself isn't a fuzzer. It's a framework with which the BFF fuzzer is built.

Tried it now in a Win7 VM, installed BFF with the installer, moved files from windows directory to my BFF directory .. yielded the same error. The file it says is missing is actually there ..

**Comment by wdormann** [comment]
"moved files from windows directory to my BFF directory"

This makes it seem that you did something other than just install BFF in a Windows VM, which runs a default fuzzing campaign at the end.  If you did this, I suppose you're on your own in figuring out what you did to make it not work.

**Comment by Kwame-NrD** [comment]
Out of the box, BFF does run a default fuzzing campaign on convert.exe using seedfiles already in there. It yielded the same error. I then copied files from certfuzz_develop\src\windows to my C:\BFF replaced the files there with those from windows dir. tried again same error.

**Comment by wdormann** [comment]
If you can provide the exact output of a clean BFF install on a machine that doesn't have a C:\BFF\ directory, I may be able to help.  There shouldn't even be a certfuzz_develop directory to copy from.  BFF installs no such directory.

**Comment by Kwame-NrD** [comment]
![err](https://user-images.githubusercontent.com/18098991/99206573-0075ff00-27bc-11eb-94a6-ea2e982beead.PNG)
![log](https://user-images.githubusercontent.com/18098991/99206575-010e9580-27bc-11eb-945e-2781d4c5243b.PNG)
Here's the error and log. This is a completely fresh installation of BFF. 
the C:\BFF directory was created during BFF installation.

**Comment by wdormann** [comment]
Given the context in the screenshots, BFF is failing when it tries to run cdb.exe.  The BFF installer configures the Windows debugger to be in the PATH, so invoking cdb from a command prompt will invoke the installed cdb.exe regardless of the current directory.

If you cannot successfully execute cdb from the same command prompt from which you attempted to run BFF, then this is a problem.  Did you run BFF from the start menu shortcut that the installer created?

Also based on the screenshots above, BFF is using Anaconda Python.  This isn't supported.
It's possible that you might be able to get it working with Anaconda, but I'd start by installing BFF in a VM that doesn't already have Python installed.

**Comment by Kwame-NrD** [comment]
`BFF is failing when it tries to run cdb.exe. `
This was indeed the case. I got it fixed .. Thank you very much for your help !
