### ISSUE TITLE
Question: Parallel Fuzzing

### ISSUE THREAD

**Issue by JeffreyShran** [CERTCC/certfuzz#39]
Hi,

I was wondering if you (or anyone) really had any suggestions on how I might accelerate the fuzzing process by introducing some sort of parallel workflow without repeating tests?

Thanks for the great product!

**Comment by wdormann** [comment]
Hi Jeffrey,

As the name suggests, BFF is quite basic and has no built-in parallel capabilities.  A workflow to use BFF in a parallel manner would be with multiple virtual machines.   e.g., if you have a 32-core system, fire up at least 32 virtual machines to improve your throughput.
